### ISSUE TITLE
Reference to a tag/branch instead of commit ID

### ISSUE THREAD

**Issue by jpkrohling** [l2x6/srcdeps-maven-plugin#4] opened 2015-08-28 09:42 UTC
Allow a project to reference a tag/branch instead of a commit ID. Not sure branch will be useful (or even desirable/recommended), but the same code for tags could be used for branches.

**Comment by ppalaga** [comment] 2015-08-28 15:42
Duplicate of https://github.com/l2x6/srcdeps-maven-plugin/issues/5

**Closed as completed** 2015-08-31 20:11 UTC
Labels: duplicate, enhancement
